### PR TITLE
Do not evaluate chunks that update data #184

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by michaeldorman** [comment]
Not sure I understand, what is the downside of frequent updating the outputs?

Never evaluating those code chunks can make it more difficult to spot problems, since the outputs are also imported in other code sections. IMHO we need to have a way to run all of those code sections at least periodically (manually that would required deleting the `eval: false` lines, is there an automatic way?)

**Comment by Robinlovelace** [comment]
Only downside: the repo size grows with every commit. Lots of commits associated with large files will make the repo size grow quick. Could we just not evaluate writing the large files?

**Comment by michaeldorman** [comment]
I see, thanks! This makes sense. It's just that would be convenient to have some mechanism to run all of those code chunks just to make sure the output is the same as expected by subsequent code. (worst case scenario is just to delete the `eval:false` lines, run the book, and then add them back in.)

**Comment by Robinlovelace** [comment]
> I see, thanks! This makes sense. It's just that would be convenient to have some mechanism to run all of those code chunks once in a while, just to make sure the output is the same as expected by subsequent code. (worst case scenario is just to delete the `eval:false` lines, run the book, and then add them back in.)

Yes would be nice to automate it monthly or so. We'll just keep an eye out and do it manually is my thinking!

Not saying this 100% solves the problem but should mitigate it and hopefully not create too many new ones.

**Pull request merged**
