### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JoshCole-DTA**
Added kernel

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Looks good to me. Look good to you @anitagraser / others?

**Comment by anitagraser** [comment]
Sorry, I have no experience with this functionality

**Comment by michaeldorman** [comment]
I recently had to do something similar to be able to choose a venv environment within VScode:

```sh
python -m ipykernel install --user --name venv --display-name "Python (venv)"
```

so I'm in favor of this addition, thanks!

**Comment by Robinlovelace** [comment]
Thanks Anita and Michael, and @JoshCole-DTA, will merge. Anything else on `venv`s, which are outside my knowledge, welcome.

**Pull request merged**
