### PR TITLE
Use subplots, fix #230

### LINKED ISSUE #230: Some figures are stretched
Some of the figures are stretched, for example:
https://py.geocompx.org/03-spatial-operations#fig-raster-slope
image

Interestingly, they look fine in the local version:
image

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Update isn't perfect but it works:

image


There may be other examples where we need to do this so putting as PR, feel free to merge @michaeldorman

**Comment by Nowosad** [comment]
@michaeldorman there is also a third possible solution (I do not know if the best): you could show the shorter code, but instead of running it -- you could just provide an image in that place (just remember to redo the code when the quarto fix is ready).

**Comment by michaeldorman** [comment]
> @michaeldorman there is also a third possible solution (I do not know if the best): you could show the shorter code, but instead of running it -- you could just provide an image in that place (just remember to redo the code when the quarto fix is ready).

Right, didn't think of that! This is an interesting alternative. IMHO @Robinlovelace 's solution is preferable, because the entire book shows the code as-is, so we should try to stick to that. It it's just temporary then you're right it would be nice to have this kind of setup with alternative images, but it comes at a cost of lots of work to prepare and manage the images and keep track of their reproducibility, so I'd still lean towards @Robinlovelace 's solution to keep things straightforward

**Comment by Robinlovelace** [comment]
Closing this PR because it will soon be a non-issue and fixed upstream: https://github.com/quarto-dev/quarto-cli/issues/9927#event-13105363395

**Comment by Robinlovelace** [comment]
Related thought: should we start an [impact.csv](https://github.com/geocompx/geocompr/blob/main/misc/our-impact.csv) for this book?

**Pull request closed without merging**
