### PR TITLE
Add upstream testing workflow, close #207

### LINKED ISSUE #207: Add workflow to test on latest pkgs versions
As suggested by @martinflies, it would be useful to test on dev versions of packages.

I think the following should do it:

```
name: Latest Versions
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/geocompx/docker:python
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          conda env update --file environment.yml --prune
      - name: Render
        run: |
          # test code:
          quarto render
          ls docs

### PR DESCRIPTION
**Pull request by Robinlovelace**
@martinfleis your thoughts would be appreciated, does this solve it? Thanks!

### CODE REVIEW

**Comment by Robinlovelace** [comment]
The workflow is running now... https://github.com/geocompx/geocompy/actions/runs/6677253079/job/18147073177

**Comment by Robinlovelace** [comment]
That failed fast! No conda in that image of course...

image

Trying again with pip.

**Comment by Robinlovelace** [comment]
Results, in progress: https://github.com/geocompx/geocompy/actions/runs/6677262371/job/18147094463

**Comment by Robinlovelace** [comment]
Finally it's working, new pkgs being installed!

image

Source: https://github.com/geocompx/geocompy/actions/runs/6677334686/job/18147259476

**Comment by Robinlovelace** [comment]
I think this is ready to merge. Good news: our book seems to work with all versions of the latest packages :tada:

**Comment by martinfleis** [comment]
Looks okay to me. I would normally just remove pins to check latest but updating them with `pur` (which I never heard of before, so thanks!) seems to work as well.

**Comment by Robinlovelace** [comment]
Me neither, a bit of a rabbit hole you've set me off there Martin! How would you remove pins? Possibly a simpler option. On a different but related note I cannot recall how we created the requirements.txt file, with [`pip freeze`](https://pip.pypa.io/en/stable/cli/pip_freeze/) like this?


Activate the environment as follows:

```bash
micromamba activate geocompy
```

Install kernel, this will allow you to select the environment in vscode or IPython as follows:

```bash
python -m ipykernel install --user
```

You can now reproduce the book (requires quarto to be installed):

```bash
micromamba run -n geocompy quarto preview
```

Optionally, to update the requirements.txt file based on your newly installed packages, run the following:

```bash
pip freeze > requirements.txt
```

Thinking of more updates to the README..

**Comment by Robinlovelace** [comment]
That approach with `pip freeze` generates a weird output:

```
+++ b/requirements.txt
@@ -17,3 +17,173 @@ xarray==2023.10.1
 Cartopy==0.22.0
 osmnx==1.7.0
 contextily==1.4.0
+affine @ file:///home/conda/feedstock_root/build_artifacts/affine_1674245120525/work
```

**Comment by martinfleis** [comment]
I doubt your requirements are based on pip freeze and I would advise against it. Pip freeze gives you everything in the environment, requirements typically have only a subset you directly need. My bet is that someone pinned that manually.

**Comment by Robinlovelace** [comment]
> I doubt your requirements are based on pip freeze and I would advise against it. Pip freeze gives you everything in the environment, requirements typically have only a subset you directly need. My bet is that someone pinned that manually.

Make sense but do you see the problem: we need an automated way to go from `environment.yml` to `requirements.txt` or vice versa. I think we found a solution but I cannot recall it and I'm not sure if it constitutes best practice. Or we abandon one of these config files.

**Comment by martinfleis** [comment]
If you kept both without pins, you wouldn't have this issue :). You could write a simple script to do that. Requirements.txt can be copypasted to the yml file and all should work.

**Pull request merged**
