### PR TITLE
readme clean

### PR DESCRIPTION
**Pull request by Robinlovelace**
- Shift readme to quarto
- Update binder, lets see if it  works

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Regarding Binder, it did work last time I tried it: 

image

However, the image was v. out of date. Let's try with the updated settings...

**Comment by itamarst** [comment]
You probably want to tell people to install with `pip` inside a virtualenv.

**Comment by Robinlovelace** [comment]
> You probably want to tell people to install with `pip` inside a virtualenv.

Aha, good idea, so as not to install system-wide right?

**Comment by Robinlovelace** [comment]
So it would be something like:

```bash
python3 -m venv geocompy
source geocompy/bin/activate
pip install -r requirements.txt
```

Right? Looking at this: https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/

**Comment by Robinlovelace** [comment]
Regarding Binder, it does actually work now. Worth re-adding mention of it to the README?

image

**Comment by Robinlovelace** [comment]
The working bit: 

image

**Comment by itamarst** [comment]
Isolation is good reason for venv, but also system-wide installation is starting to be unsupported on newer Linux distributions, so people will get mysterious errors if they try to install globally.

**Comment by Robinlovelace** [comment]
Think this is good to merge. Unless  there  are any objections plan to do so today. Also if you're working on this ATM @michaeldorman (have seen your recent commits), quick review appreciated. Feel free to merge  also.

**Comment by michaeldorman** [comment]
> Think this is good to merge. Unless there are any objections plan to do so today. Also if you're working on this ATM @michaeldorman (have seen your recent commits), quick review appreciated. Feel free to merge also.

Looks good to me, thanks @Robinlovelace and everyone

**Pull request merged**
