### PR TITLE
Updates to c1

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
The latest commit aims to make Chapter 1 more readable. There were too many bullet points I think. I've moved the technical description of packages down and the broad intro to data models up, hope it's better, review comments welcome.

**Comment by michaeldorman** [comment]
Looks great, thanks @Robinlovelace ! The only thing I'm not sure about is `warning:false`, perhaps this can be misleading for users who run the code and see a warning that's not in the book, and may think they did something wrong. I suggest to follow @Nowosad 's suggestion to replace the examples in a way that we don't demonstrate "wrong" workflows, such as areas, centroids, etc. in a geographic CRS. What do you think?

**Comment by Robinlovelace** [comment]
> I suggest to follow @Nowosad 's suggestion to replace the examples in a way that we don't demonstrate "wrong" workflows, such as areas, centroids, etc. in a geographic CRS. What do you think?

Good idea, I guess we could project a subset of countries into a local CRS and then compute the centroids.

**Comment by michaeldorman** [comment]
> > I suggest to follow @Nowosad 's suggestion to replace the examples in a way that we don't demonstrate "wrong" workflows, such as areas, centroids, etc. in a geographic CRS. What do you think?
> 
> Good idea, I guess we could project a subset of countries into a local CRS and then compute the centroids.

Sure, it's also a good option!

**Comment by Robinlovelace** [comment]
> Sure, it's also a good option!

That was written before I saw your 'envelope' solution. That works too, with fewer lines of code, so +1 to that.

**Pull request merged**
